### ISSUE TITLE
[Feedback] michalpolko's ICC version

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#76]
Lord Marrowgar:
- Coldflame (http://www.wowhead.com/spell=69146) Graphically is showed correctly but no damage to raid.
- Bone Storm works fine, but cross fire does not make damage either.
- Mayor bug: Bone Spike Graveyard (http://www.wowhead.com/spell=69057) even if raid destroy it, players remains rooted. Not possible casting or move even if dies and druid resurrect it. Only way is to die and "release" to get back in instance.

Lady Deathwhisper:
- Dominate Mind (http://www.wowhead.com/spell=71289) does not work.
- When lady is below 40% hp. Some npcs come to kill, this must not happen afaik.
  Those npcs are:
  Kor'kron Stalker (http://www.wowhead.com/npc=37028/).
  Kor'kron Defender (http://www.wowhead.com/npc=37032)
  Kor'kron Reaver (http://www.wowhead.com/npc=37920)
  Kor'kron Primalist (http://www.wowhead.com/npc=37030)
  Kor'kron Templar (http://www.wowhead.com/npc=37034)
  Kor'kron Vanquisher (http://www.wowhead.com/npc=37035)

Deathbringer Saurfang:
- Works perfect, but have Lady Deathwhisper dialogs.

Rotface
- At least in 25 mode, Mutated Infection (http://www.wowhead.com/spell=69674) is properly casted to 2 raid members, but the following spells does not work:
  Sticky Ooze (http://www.wowhead.com/spell=69774)
  Weak Radiating Ooze (http://www.wowhead.com/spell=69750)
  Radiating Ooze (http://www.wowhead.com/spell=69760)
  Unstable Ooze (http://www.wowhead.com/spell=69558)
  Unstable Ooze Explosion (http://www.wowhead.com/spell=69839)
- Ooze Flood (http://www.wowhead.com/spell=69789) does not work too.

Sindragosa
- Unchained Magic (http://www.wowhead.com/spell=69762) must not be casted to tanks, also must not damage people making melee damage.
- Fly Phase:
  · Sometimes when use Frost Beacon (http://www.wowhead.com/spell=70126) any Ice Tomb (http://www.wowhead.com/spell=70157) appeas so not possible protection from Frost Bomb (http://www.wowhead.com/spell=69846).
  · Others works fine ;-)

This is all for now, still testing to bring remaining bosses feedback.

**Comment by carlos93** [comment]
About lady, when mana barrier wears off, she cast frostbolt on all hostile targets in default visibility instance = 400 ~ 500 yards and hit the horde warriors in the upper floor ;)

**Comment by michalpolko** [comment]
Marrowgar:
- persistent aoe auras are bugged in some weird way, where only 1 aura cast by given caster works or something like that, not fully researched, so this one doesnt work properly as well (but does work sometimes). those aoes need repairing cuz it also affects pvp (on battlegrounds where are more than 1 hunters with traps or DKs with slowing aoe etc.)
- Impale doesnt get removed - this was bugged by some recent commit in mangosR2 (I did update a few days ago on my serv and it got bugged), I havent checked it yet so no more comment about this

Lady:
- aoe mind control not implemented in core. I was thinking about implementing faction change and maybe losing control over the character like in Blind or similiar spell, maybe autoattacking some random ally, will see
- pulling npcs: lol, this sucks, I will have to make some checks for every aoe spell with big radius not to target creatures ;x

Saurfang:
- you are using some custom script texts, use official sd2 ones

Rotface:
- i heard that Mutating Infection stopped working some time ago or at least summoning of oozes, ill check that
- ooze flood maybe doesnt work due to changes with unit flags, i will have to test it

Sindragosa:
- unchained magic targeting criteria is having mana power type, so if somebody has mana he can be a target of this. what do You think should be checked when selecting target for this? class maybe? what about enh/ele shamans in such case?
- You mean that sometimes there are no Ice Tombs? I saw such situation, don't know why it happens

> Others sindragosa cast Ice Tomb (http://www.wowhead.com/spell=70157) to all raid members and restarts itself.

I dont understand this one ;P

Thx for feedback :) I will try to check those things asap after finishing Lich King.

**Comment by michalpolko** [comment]
Fixed Impale https://github.com/mangosR2/scriptdev2/commit/0e37d5a09004913f888f6c43ce0acd0cc6454542

and Frostbolt Volley https://github.com/mangosR2/mangos/commit/53328fa83610eae08c44670e7614dc804f68dd31
although Frostbolt Volley shouldnt ignore LoS imho, but I have no time for researching this ;P

**Comment by michalpolko** [comment]
Hm, there are more spells with problem like that ;/
AoE spells cast by bosses seem to ignore LoS and why is that? ;/

**Comment by michalpolko** [comment]
Please explain this part:

> Others sindragosa cast Ice Tomb (http://www.wowhead.com/spell=70157) to all raid members and restarts itself.

cuz I dont know if there is a bug or there isn't ;p

**Comment by Undergarun** [comment]
Never mind michalpolko, understanding problem with my users ;-)

**Comment by Sar777** [comment]
Does anyone have a problem with Sindragosa, in phase 2 when it takes off and if the raid is on the ladder, she leaves the battlefield and takes the place: (

**Comment by Undergarun** [comment]
Some spells missing due to hacky implementation.

**Comment by rsa** [comment]
https://github.com/scriptdev2/scriptdev2/commits/icc_project
see in this... I'm crying: (

**Comment by softbest** [comment]
Hola Undergarun como he podido ver estas introduciendo las traducciones de la ciudadela de hielo al español (https://github.com/mangosR2/scriptdev2/commit/0c4952ba7309fb7106777f419d3538db5eef478a) no se de donde las estas sacando o si las estas haciendo tu pero lo más posible es que estés sacando los locales del proyecto de traducción eswow2 ( antiguo loes2) que prácticamente tiene todo el wow o si es así hazlo ya que es así por que esas traducciones de la ciudadela de hielo están en dichas traducciones y para que lo veas te lo he subido : http://pastebin.com/7iK5yRRh
Si usas estas traducciones en el repo de mangosR2 por favor pon creditos al equipo de Eswow2 en el commit de las traducciones y si te preguntas quien soy pues Nomad exadmin del proyecto de traducción
Un saludo

**Comment by Undergarun** [comment]
Las traducciones estan hechas usando .debug play sound ID y escritas manualmente. No me fio de ningún proyecto de traducción externo, no tengo intención alguna de introducir contenido sin comprobarlo ya que muchas de las traducciones que haceis son traduciendo del inglés directamente y no usando Caches o .debug play sound ID y otras tantas veces ni siquiera coinciden los audios con los textos. Las traducciones al completo llevan hechas bastante y las iré introduciendo cuando tenga tiempo.

**Comment by VirusGoD** [comment]
В ЦЛК пропала аура "сила ринна" http://ru.wowhead.com/spell=73762
Говорят в стартовой локации ДК тоже аура пропала."Власть над Акерусом" http://ru.wowhead.com/spell=51721

**Comment by Mrbytes** [comment]
<Undergarun>
No tienes ni idea de lo que dices, no sabes como trabajamos, tu flipas, me apuesto contigo, que ni has respetado comas, exclamaciones, ni pausas, debido a como lo haces, veras, colega en eso... ¡EsWoW2 tiene que enseñarte!, y tienes que aprender mucho.

**Comment by Undergarun** [comment]
Salvo los textos de instances, el resto lo saco de un parseador de wowhead escrito en C# y un parseador de caches. No necesito depender de proyectos de terceros y no me interesan. Las traducciones de ICC no son vuestras y no voy a mencionaros en ningún commit. No hay más que hablar...

**Comment by Mrbytes** [comment]
5mentarios... te dejo columpiandote en tu ignorancia con respecto a nuestro trabajo.

**Comment by carlos93** [comment]
Chicas no discutais, si alguien quiere las traducciones de eswow2 ya las cogerá de su página, no hace falta que vengas a hacer publi. Si no las quieren aceptar es cosa suya :S

**Comment by Faq** [comment]
cmon could u speak atleast eng/rus, or pm each other so dont spam here?

**Comment by michalpolko** [comment]
They are talking about some "chicks" ;x

**Comment by carlos93** [comment]
https://github.com/Radicalmangos/devmangos/commit/e6287e51e1facd8a94056745e83aab012d295a86

More "blizzlike" ;)

**Comment by michalpolko** [comment]
https://github.com/mangosR2/mangos/commit/77341bcffeaf66e3ce37384239d840c6afee5ef1

**Comment by carlos93** [comment]
https://github.com/Radicalmangos/devmangos/commit/22859ac9b19b5e63da71ca9575592ba7501f4fae

Better this, with triggered spell ;).

**Comment by rsa** [comment]
wow. i like discussion like this :)

**Comment by rsa** [comment]
@michalpolko, all spells in R2 now checked on GO-in-LOS (with config option CheckGOInPath=1). need check with ice tomb of Sindra.

**Comment by michalpolko** [comment]
https://github.com/mangosR2/mangos/commit/0333c334404ebe87350e3b11c14d930c72b3875a
https://github.com/mangosR2/scriptdev2/commit/d6b147b57bd28815db4b95ed6391b13747aa202e

I trust You checked this and the spell is actually triggered, because we cast Icy Grip as not triggered and then Blistering Cold as not triggered in handling the effect of Icy Grip, which imho shouldnt work ;P So confirm that it works pls.

**Comment by carlos93** [comment]
Yes, the 1st commit wasn't tested but the last works correctly ;).

**Comment by Undergarun** [comment]
New complete report comming soon ;-)
