### ISSUE TITLE
Crash in Halls_of_reflection r0356

### ISSUE THREAD

**Issue by KiriX** [mangosR2/scriptdev2#88]
https://gist.github.com/1711885

Crash at instance script begining.

Краш в самом начале работы скрипта инсты - тётка что-то щебечет и в какой-то момент - краш.
MR2 1647, SD2R2 0356

**Comment by rsa** [comment]
а сам-то краш иде?

**Comment by KiriX** [comment]
Эмс... Не понял, я же приложил крашдамп на гисте.
Первая строка репорта - ссылка на него...

**Comment by rsa** [comment]
перепроверил за обе фракции. нет краша. судя по дампу - база криво залита.
PS народ, ну ведь всех прошу перепроверить на тестовом а потом рапортовать. неужели сложно?

**Comment by Venom** [comment]
what's so different between master and testing repository???

halls of reflection crash at starting is DB problem.  i had it ones.

it's because YTDB db and R2 sql Boss GuIDE was diffrent.  there was 4 bosses spawning instead of 2. at starting....
and 4 bosses started event.  that was making server crash....

**Comment by rsa** [comment]
"testing" - not branch "testing", but MangosR2 test server (see wiki)
