### ISSUE TITLE
Ice Bomb (Sindragosa)

### ISSUE THREAD

**Issue by carlos93** [mangosR2/scriptdev2#92]
Since we have mmaps, the damage of Ice bomb and other spells (Vile gas , festergut) stop working. I don't know if it's only on my server.

Anyone has the same problem?

**Comment by Undergarun** [comment]
As already said, remove mmaps from raids and instances. Only use on arenas, battegrounds and main continents. Maybe some instances that don't use scripted movements can also use mmaps.

**Comment by michalpolko** [comment]
I don't think that it is related to mmaps.
If this is the spell that she casts in air phase, then it was broken after some commit (related to delayed spells? missiles? dont know).
I use mmaps in ICC with no problems, only in Lich King encounter I will have to set special flag for mobs to make them not use pathfinding, because platform is a gameobject.

**Comment by rsa** [comment]
i restore old (my) sindragosa script with dummy targets - with his all work fine. with mmaps.

**Comment by carlos93** [comment]
I don't know why but that's spells stop working :(. Can you help me?

**Comment by Angarius** [comment]
I comfirm the problem! 
I know not even what it is.

**Comment by Sar777** [comment]
Somehow, from the spell does not spawn mob.
It is certainly possible through SummonCreature, but it is not good :(
For example 69846

**Comment by Sar777** [comment]
https://github.com/mangosR2/mangos/commit/a9bc5dd6e54dea1b235661316d4f4310ad1dd6b6
